const WEBHOOK_SUBSCRIPTION_STATUS = {
  SUBSCRIBED: "subscribed",
  UNSUBSCRIBED: "unsubscribed",
};

const VALID_WEBHOOK_STATUS = new Set([
  WEBHOOK_SUBSCRIPTION_STATUS.SUBSCRIBED,
  WEBHOOK_SUBSCRIPTION_STATUS.UNSUBSCRIBED,
]);

module.exports = {
  WEBHOOK_SUBSCRIPTION_STATUS,
  VALID_WEBHOOK_STATUS,
};
